
<html>
<head>
    <base href="<?php echo APP_ROOT;?>">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet">

    <link href="src/content/painel/css/style.css" type="text/css" rel="stylesheet">
    <link href="src/content/painel/css/sidebar.css" type="text/css" rel="stylesheet">

    <script src="https://kit.fontawesome.com/b044f23397.js" crossorigin="anonymous"></script>

    <script> window.Area = '<?php echo APP_AREA;?>'; </script>
</head>
<body class="bg-light">



<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Offcanvas navbar</a>
        <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#/home">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#/pessoa">Pessoa</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">Configurações</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown01">
                        <li><a class="dropdown-item" dialog="open" uri="dicionario/form/gerarportabela" title="Gerar Dicionário de Rotina" size="md">Gerar Dicionário de Rotina</a></li>
                        <li><a class="dropdown-item" href="#/dicionario">Manutenção Dicionário de Rotina</a></li>
                        <li><a class="dropdown-item" href="#/versao">Versão de Banco de Dados</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<?php $this->Render();?>

</body>
</html>